Week2
frizzby/coyote-leg pull request #3
Opened 2017-12-21 17:57 UTC by mikhailgladchenko

solutions for week2 tasks

2017-12-28 23:27 UTC, frizzby requested changes

2017-12-28 23:27 UTC, frizzby commented on week2/ex4_done.py
> +
```python
print(User("mikhail", 57) == User("mikhail", 57))
```
Check this test case.

2017-12-28 23:27 UTC, frizzby commented on week2/ex1_done.py
> +def main():
Please add more test cases. Test corner cases (like empty string, etc) as well.

2017-12-28 23:27 UTC, frizzby commented on week2/ex2_done.py
> +def main():
Please add more test cases.

2017-12-28 23:27 UTC, frizzby commented on week2/ex3_done.py
> +        self._mutator = mutator
What is `mutator`? Why you need it here?

2017-12-28 23:27 UTC, frizzby commented on week2/ex3_done.py
> +            self._counter = collections.Counter()
The tasks asks to implement your own Counter class. Not to wrap around the standard one. 
Your code should have no references to `collections.Counter`

2018-01-02 22:29 UTC, frizzby commented on week2/ex4_done.py
> +
what about this?

2018-01-03 23:11 UTC, frizzby requested changes

2018-01-03 23:11 UTC, frizzby commented on week2/ex3_mycounter_done.py
> +        return mc
This has not the same return value as in [`collections.Counter`](https://docs.python.org/3/library/collections.html#collections.Counter.most_common). Please make it equivalent.

2018-01-03 23:11 UTC, frizzby commented on week2/ex3_mycounter_done.py
> +            if counter < n:
Instead of counting n items, you can just slice n first elements: `sorted(...)[:n]`

2018-01-03 23:11 UTC, frizzby commented on week2/ex3_done.py
> +# 3.	Elements counting. It refers to the sections 1.12 and 1.4-1.5 of the Python Cookbook. Implement the Counter class. It should only support operations like __iter__, __getitem__ and .most_common(n
Please remove this file.

2018-01-03 23:11 UTC, frizzby commented on week2/ex2_done.py
> +    url = "page=2&foo=bar&x=y&utm_source=ss&utm_content=ccc"
This code has a few flaws.
Add more test cases and you'll see it.

This code does not retain the original params order.

2018-01-03 23:11 UTC, frizzby commented on week2/ex1_done.py
> +# 1.	Write a function that will parse a url query string like "page=2&foo=bar&x=y&utm_source=ss&utm_content=ccc" and return a query string where all the params are sorted by their names like this "fo
_all the "utm\_" parameters are removed_ here means the all parameters that START with `utm_`. But your code removes all that contain _utm\__ substring.

2018-01-03 23:11 UTC, frizzby commented on week2/ex1_done.py
> +        new_url += "{}={}{}".format(key, params_dict[key], "&")
Don't use `+=` or `+` to build strings as it is very inefficient. Strings in python a immutable, and each concatenation creates new string. And also it hurts readability. 

Please use `["".join()](https://docs.python.org/3/library/stdtypes.html#str.join)` instead.

2018-01-03 23:11 UTC, frizzby commented on week2/ex1_done.py
> +            key = entry.split("=")[0]
`key, value = entry.split()`

2018-01-04 00:33 UTC, frizzby commented on week2/ex1_done.py
> +    for entry in string_splitted:
What you are doing here is basically filtering a list. This is very common operation in Python and it is done best with [list comprehensions](https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions):

```python
filtered = [x for x in string_splitted if not x.startswith("utm_")]
```

Another approach is to use [`filter()`](http://book.pythontips.com/en/latest/map_filter.html):
```python
filtered = filter(lambda x: not x.startswith("utm_"), string_splitted)
```


The basic operations on lists are: `filter()`, `map()`, `reduce()` ([read](http://book.pythontips.com/en/latest/map_filter.html)). Keep them in mind when dealing with lists. You can solve almost any task just with this three functions.

2018-01-05 17:49 UTC, mikhailgladchenko commented
Yan,
I’ve just pushed new code for ex3_mycounter_done with different implementations of most_common function. I have there the one that slices the list (most_common) and another one that uses heapq.nlargest api(most_common_heap).I’m not sure that the last one works as it should.Can we take a look togather on Monday?
Regards,Mikhail

From: Yan Davidovich [mailto:notifications@github.com]
Sent: Wednesday, January 3, 2018 3:11 PM
To: frizzby/coyote-leg <coyote-leg@noreply.github.com>
Cc: Mikhail Gladchenko <Mikhail_Gladchenko@epam.com>; Author <author@noreply.github.com>
Subject: Re: [frizzby/coyote-leg] Week2 (#3)


@frizzby requested changes on this pull request.

________________________________

In week2/ex3_mycounter_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159546881>:

> +            for value in values:

+                self.mydict[value] += 1

+        else:

+            self.mydict = {}

+

+    def __repr__(self):

+        return repr(self.mydict)

+

+    def most_common(self, n):

+        counter = 0

+        mc = {}

+        for key, value in sorted(self.mydict.items(), key=lambda kv: kv[1], reverse=True):

+            if counter < n:

+                mc[key] = value

+            counter += 1

+        return mc

This has not the same return value as in collections.Counter<https://docs.python.org/3/library/collections.html#collections.Counter.most_common>. Please make it equivalent.

________________________________

In week2/ex3_mycounter_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159547634>:

> +

+        if values is not None:

+            self.mydict = dict.fromkeys(values, 0)

+            for value in values:

+                self.mydict[value] += 1

+        else:

+            self.mydict = {}

+

+    def __repr__(self):

+        return repr(self.mydict)

+

+    def most_common(self, n):

+        counter = 0

+        mc = {}

+        for key, value in sorted(self.mydict.items(), key=lambda kv: kv[1], reverse=True):

+            if counter < n:

Instead of counting n items, you can just slice n first elements: sorted(...)[:n]

________________________________

In week2/ex3_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159547714>:

> @@ -0,0 +1,98 @@

+# 3.   Elements counting. It refers to the sections 1.12 and 1.4-1.5 of the Python Cookbook. Implement the Counter class. It should only support operations like __iter__, __getitem__ and .most_common(n). Try to make it as efficient as possible in terms of performance. Think of an underlying data structure that should be used and also a base class.

Please remove this file.

________________________________

In week2/ex2_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159548467>:

> +        except IndexError:

+            pass

+        if "utm_" not in key:

+            params_dict[key] = value

+    keys_original = (params_dict.keys())

+    new_url = ""

+

+    for key in keys_original:

+

+        new_url += "{}={}{}".format(key, params_dict[key], "&")

+

+    return None if new_url == str("=&") else new_url[0:-1]

+

+

+def main():

+    url = "page=2&foo=bar&x=y&utm_source=ss&utm_content=ccc"

This code has a few flaws.
Add more test cases and you'll see it.

This code does not retains the original params order.

________________________________

In week2/ex1_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159548783>:

> @@ -0,0 +1,39 @@

+# 1.   Write a function that will parse a url query string like "page=2&foo=bar&x=y&utm_source=ss&utm_content=ccc" and return a query string where all the params are sorted by their names like this "foo=bar&page=2&x=y" and all the "utm_" parameters are removed.

all the "utm_" parameters are removed here means the all parameters that START with utm_. But your code removes all that contain utm_ substring.

________________________________

In week2/ex1_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159549154>:

> +    params_dict = {}

+    for entry in string_splitted:

+        key = value = ""

+        try:

+            key = entry.split("=")[0]

+            value = entry.split("=")[1]

+        except IndexError:

+            pass

+        if "utm_" not in key:

+            params_dict[key] = value

+    keys_sorted = sorted(params_dict.keys())

+    new_url = ""

+

+    for key in keys_sorted:

+

+        new_url += "{}={}{}".format(key, params_dict[key], "&")

Don't use += or + to build strings as it is very inefficient. Strings in python a immutable, and each concatenation creates new string. And also it hurts readability.

Please use ["".join()](https://docs.python.org/3/library/stdtypes.html#str.join) instead.

________________________________

In week2/ex1_done.py<https://github.com/frizzby/coyote-leg/pull/3#discussion_r159549386>:

> @@ -0,0 +1,39 @@

+# 1.   Write a function that will parse a url query string like "page=2&foo=bar&x=y&utm_source=ss&utm_content=ccc" and return a query string where all the params are sorted by their names like this "foo=bar&page=2&x=y" and all the "utm_" parameters are removed.

+

+

+def parse_url(url):

+    string_splitted = url.split("&")

+    params_dict = {}

+    for entry in string_splitted:

+        key = value = ""

+        try:

+            key = entry.split("=")[0]

key, value = entry.split()

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/frizzby/coyote-leg/pull/3#pullrequestreview-86514315>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Agzo8RpcvJxOlN201cPkNXwlp-TUJ5q8ks5tHAkUgaJpZM4RKKEA>.

2018-01-10 02:34 UTC, merged